Lection 3: task 2 - template page
js-tasks-ru/htmlcss-20210513_pav-mishchenko pull request #10
Opened 2021-05-25 10:34 UTC by mindk-pmishchenko

2021-05-25 10:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-26 10:23 UTC, GSemikozov requested changes

2021-05-26 10:23 UTC, GSemikozov commented on components/page-template/page-template.css
> +  margin-left: 165px;
вместо этого можем либо обернуть page-template__main в универсальный контейнер page__box, либо скопировать стили из него в сам page-template__main - `margin: 0 auto; max-width: 1110px`

2021-05-26 10:23 UTC, GSemikozov commented on components/page-template/page-template.css
> +.menu {
.main и .component - в конечном итоге будут отдельными компонентами, поэтому сразу можем вынести эти стили в отдельные файлы

2021-05-26 12:27 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-26 12:28 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-26 12:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-26 12:31 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-26 12:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-26 12:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-26 14:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-26 14:21 UTC, mindk-pmishchenko commented on components/page-template/page-template.css
> +  margin-left: 165px;
перенес  в page-template__main

2021-05-26 14:21 UTC, mindk-pmishchenko commented on components/page-template/page-template.css
> +.menu {
вынес

2021-05-26 14:21 UTC, mindk-pmishchenko commented
@GSemikozov всё исправил

2021-05-26 15:16 UTC, GSemikozov approved these changes, later dismissed

2021-05-26 15:16 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2021-05-27 07:11 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-27 07:12 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-27 07:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-27 08:30 UTC, GSemikozov approved these changes

2021-05-27 08:30 UTC, merged