Lection 4: task 2 - background image
js-tasks-ru/htmlcss-20210513_pav-mishchenko pull request #12
Opened 2021-05-28 09:13 UTC by mindk-pmishchenko

2021-05-28 09:13 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-30 08:45 UTC, GSemikozov requested changes

2021-05-30 08:45 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +@media screen {
вместо такого медиа-запроса (который по сути ничего не делает) дефолтный background-image лучше сразу определить у самого элемента выше

2021-05-30 11:32 UTC, mindk-pmishchenko commented on 06-lection4/02-background-image/background-image.css
> +@media screen {
согласен, увлёкся

2021-05-30 11:50 UTC, GSemikozov approved these changes

2021-05-30 11:50 UTC, merged