Lection 4: task 4 - mobile view
js-tasks-ru/htmlcss-20210513_pav-mishchenko pull request #15
Opened 2021-05-28 13:13 UTC by mindk-pmishchenko

2021-05-28 13:14 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-30 08:54 UTC, GSemikozov requested changes

2021-05-30 08:54 UTC, GSemikozov commented on components/card/card.css
>    padding: 80px 25px 30px;
мне кажется, здесь слишком большие паддинги - лучше на всякий случай свериться с дизайном. Если все ок - просьба написать об этом тут же в комментарии

2021-05-30 08:54 UTC, GSemikozov commented on components/card/card.css
>    margin: 0 30px 30px;
внешнее поведение (то как блок ведет себя относительно других блоков) мы определяем всегда через родителя (если следовать БЭМ), через миксы, поэтому - отсюда марджины мы можем убрать, и затем определить их через родительский блок в которых будем встраивать карточки

2021-05-30 08:54 UTC, GSemikozov commented on components/card/card.css
> +    margin: 0 8px 11px;
та же история, описанная в комменте выше)
перенесем эти стили к контейнеру через который задается внешнее поведение карточкам (условно готовя - .container, .container__card (этот класс определяющий поведение будет рядом с классом блока .card))

2021-05-30 08:54 UTC, GSemikozov commented on components/page-template/page-template.css
> +  .page-template__header {
вот здесь, кстати, советую переиспользовать тот хедер который у нас уже сверстан - разница будет лишь в том что в данном темплейте в хедере будет только верхняя секция + поменяем фон через класс-модификатор. И тогда высоту хедера не надо фиксировать. И тоглер меню - перенесем в основной хедер.

2021-05-30 10:51 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-30 10:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-30 10:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-30 11:01 UTC, mindk-pmishchenko commented on components/card/card.css
>    padding: 80px 25px 30px;
да, мой косяк - не знаю откуда я брал эти падинги

2021-05-30 11:29 UTC, mindk-pmishchenko commented on components/card/card.css
>    margin: 0 30px 30px;
переделал

2021-05-30 11:29 UTC, mindk-pmishchenko commented on components/card/card.css
> +    margin: 0 8px 11px;
перенес

2021-05-30 11:29 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-30 11:29 UTC, mindk-pmishchenko commented on components/page-template/page-template.css
> +  .page-template__header {
спасибо, согласен
сделал 1 хедер и использовал на 2х страницах

2021-05-30 11:31 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-30 11:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-30 11:37 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-30 11:48 UTC, GSemikozov requested changes

2021-05-30 11:48 UTC, GSemikozov commented on components/cards/cards.css
> +  margin: 0 30px 30px;
а эти отступы не отнаследуются для карточек на мобилке?

2021-05-30 12:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-30 12:35 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-30 12:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-30 12:37 UTC, mindk-pmishchenko commented on components/cards/cards.css
> +  margin: 0 30px 30px;
они перекрылись марджинами для .card с мобильныхх стилей, которые я забыл исправить)
перенес - сделал правильно)

2021-05-30 12:49 UTC, GSemikozov submitted a review, later dismissed

2021-05-30 12:49 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2021-05-30 12:55 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-30 16:42 UTC, GSemikozov approved these changes

2021-05-30 16:42 UTC, merged