Lection 5: task 4 - inputs
js-tasks-ru/htmlcss-20210513_pav-mishchenko pull request #20
Opened 2021-06-01 13:48 UTC by mindk-pmishchenko

2021-06-01 13:49 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-02 07:02 UTC, GSemikozov requested changes

2021-06-02 07:02 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +  width: 350px;
по ширине, как и в случае с кнопками, можем не использовать фиксированное значение, а если надо растянуть по родителю - делаем это через модификатор

2021-06-02 07:55 UTC, mindk-pmishchenko commented on 07-lection5/04-input/input.css
> +  width: 350px;
ну да, он и так по ширине родителя растягивается. согласен

2021-06-02 07:55 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-02 07:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-02 09:30 UTC, GSemikozov approved these changes, later dismissed

2021-06-02 09:39 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2021-06-02 09:44 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-02 09:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-02 09:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-03 09:13 UTC, GSemikozov approved these changes

2021-06-03 09:13 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2021-06-03 09:18 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-03 09:24 UTC, GSemikozov approved these changes

2021-06-03 09:24 UTC, merged