Lection 5: task 5 - main page with components
js-tasks-ru/htmlcss-20210513_pav-mishchenko pull request #24
Opened 2021-06-04 10:34 UTC by mindk-pmishchenko

2021-06-04 10:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-04 11:12 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-04 14:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-04 14:41 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-04 19:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-04 19:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-04 20:04 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-04 20:05 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-04 20:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-04 20:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-04 20:20 UTC, GSemikozov requested changes

2021-06-04 20:20 UTC, GSemikozov commented on components/page/page.css
> +  padding-left: 125px;
вот тут не уверен что так стоит делать. Речь идет о табах как внутреннее меню страницы в хедере? Если да, то оно встроено в стандартные контейнер (.page__box) и просто выравнивается по левому краю

2021-06-04 20:20 UTC, GSemikozov commented on components/tabs/tabs.css
> +  cursor: pointer;
все-таки на этом уровне надо определить какой будет бордер (5px solid + цвет зададим прозрачный transparent) - для того чтобы при изменении стейта и при добавлении бордера не происходило скачка контента

2021-06-04 20:24 UTC, mindk-pmishchenko commented on components/page/page.css
> +  padding-left: 125px;
тогда не получится сделать адекватную отбивку таб от контента, как нарисовано в дизайне
там под табами - серая линия на всю ширину контейнера. а так она будет не заходить на паддинги или вылазить за свой контейнер...

2021-06-04 20:27 UTC, mindk-pmishchenko commented on components/tabs/tabs.css
> +  cursor: pointer;
понял о чем ты, но скачка нет - можешь посмотреть здесь https://mindk-pmishchenko.github.io/htmlcss-20210513_pav-mishchenko/

2021-06-04 20:47 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-04 20:47 UTC, mindk-pmishchenko commented on components/tabs/tabs.css
> +  cursor: pointer;
да, после того как сделал flex - начало прыгать. добавил прозрачный бордер, теперь норм

2021-06-04 20:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-05 18:29 UTC, GSemikozov commented on components/page/page.css
> +  padding-left: 125px;
а что если у нас будет огромный монитор с шириной экрана свыше 4к пикселей?
думаю, это решение все-таки не универсальное. Если еще один вариант (мне кажется, нечто подобное сделано и в иллюстративной версии проекта) - задавать бордер через :after с absolute, ставить по середине, а ширину - в несколько сот процентов (а сАмому внешнему контейнеру табов - overflow: hidden, чтобы такая длинная линия не создавала горизонтальный скрол).

2021-06-05 18:37 UTC, GSemikozov requested changes

2021-06-05 18:37 UTC, GSemikozov commented on index.html
> +              <div class="cards">
кстати, обратил внимание здесь https://mindk-pmishchenko.github.io/htmlcss-20210513_pav-mishchenko/, что сетка карточек лежит вне основного контейнера страницы (.page__box) - надо исправить. И еще - когда в карточках добавлены наши компоненты и при этом с ними можно взаимодействовать, выглядит это конечно не очень, поэтому - предлагаю где это возможно добавить стейты opened (показать компоненты в раскрытом виде) и сами компоненты в превью карточки задизейблить (через pointer-events: none) - все-таки мы должны отобразить лишь превью, а дальше - перейти по ссылке и посмотреть компонент в действии на его собственной странице

2021-06-06 09:47 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-06 09:50 UTC, mindk-pmishchenko commented on index.html
> +              <div class="cards">
а какую роль должен играть класс .page__box? у меня его нет
есть page__main и page__content - карточки лежат в них

2021-06-06 10:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-06 15:26 UTC, GSemikozov requested changes

2021-06-06 15:26 UTC, GSemikozov commented on components/page/page.css
> +  margin-left: 135px;
такой вариант будет актуален лишь для стандартного десктопа на ноутбуке, но на больших устройствах и на более мелких - работать не будет. Если нужно просто выровнять контейнер по середине, тогда - `margin: 0 auto;`

2021-06-06 15:26 UTC, GSemikozov commented on components/tabs/tabs.css
> +  margin-left: -20px;
здесь и у .tabs__scroller отрицательный отступ - выглядит как какой-то хак =) какую проблемы решают отрицательные отступы?

2021-06-07 08:10 UTC, mindk-pmishchenko commented on components/tabs/tabs.css
> +  margin-left: -20px;
исправил

2021-06-07 08:10 UTC, mindk-pmishchenko commented on components/page/page.css
> +  margin-left: 135px;
это ж минимальные отступы для десктопа по краям, чтоб на уровне с хедером/футером было. а центровка и так флексом есть
поэтому не очень понял что здесь исправить?

2021-06-07 08:10 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-07 08:10 UTC, mindk-pmishchenko commented on components/page/page.css
> +  padding-left: 125px;
исправлено

2021-06-07 08:19 UTC, mindk-pmishchenko commented on index.html
> +              <div class="cards">
исправлено

2021-06-07 08:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-07 09:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-07 10:04 UTC, mindk-pmishchenko commented on components/page/page.css
> +  margin-left: 135px;
исправил

2021-06-08 13:47 UTC, GSemikozov approved these changes

2021-06-08 13:47 UTC, merged