Lection 2: task 1 - histogram
js-tasks-ru/htmlcss-20210513_pav-mishchenko pull request #6
Opened 2021-05-21 09:59 UTC by mindk-pmishchenko

2021-05-21 09:59 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-23 12:28 UTC, GSemikozov requested changes

2021-05-23 12:28 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram/histogram.css
> +.histogram__title-row {
тут и ниже хочу предложить улучшить именование классов, чтобы они были более универсальными.
`.histogram__title-row` -> `.histogram__title`

2021-05-23 12:28 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram/histogram.css
> +.histogram__view-all-link {
`.histogram__view-all-link` -> `.histogram__link`

2021-05-23 12:28 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram/histogram.css
> +.chart {
`.chart` -> `.histogram__chart` (это все-таки элемент гистограммы, а не отдельный блок)

2021-05-23 12:28 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram/histogram.css
> +.chart__column {
`.chart__column` -> `.histogram__chart-column`

2021-05-23 12:28 UTC, GSemikozov commented on assets/css/_fonts.css
> +    font-family: 'Inter', sans-serif;
если пройтись по макету - все-таки не у всех элементов Inter =) пусть остается так - но в будущем стоит об этом помнить (что надо будет для некоторых элементов переопределить шрифт на Roboto)

2021-05-23 14:50 UTC, mindk-pmishchenko commented on assets/css/_fonts.css
> +    font-family: 'Inter', sans-serif;
мне показалось что в основном Inter, поэтому поставил как основной
так допустимо делать или лучше оставлять основным Roboto?

2021-05-23 15:11 UTC, mindk-pmishchenko commented on 04-lection2/01-histogram/histogram/histogram.css
> +.histogram__title-row {
согласен

2021-05-26 10:14 UTC, GSemikozov commented on assets/css/_fonts.css
> +    font-family: 'Inter', sans-serif;
допустимо, в общем-то. В нашем случае задействованы сразу 3 разных шрифта, поэтому - в любом случае в какой-то момент придется переопределять.

2021-05-26 12:33 UTC, mindk-pmishchenko commented
@GSemikozov конфликты зарезолвил - заапрувь плз

2021-05-26 15:14 UTC, GSemikozov approved these changes

2021-05-26 15:14 UTC, merged