Lection 2: task 2 - skeleton
js-tasks-ru/htmlcss-20210513_pav-mishchenko pull request #7
Opened 2021-05-21 11:00 UTC by mindk-pmishchenko

2021-05-21 11:01 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-23 12:21 UTC, GSemikozov requested changes

2021-05-23 12:21 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton/skeleton.css
> +.skeleton {
а зачем нам дополнительная вложенность? в смысле, путь к файлу был исправлен с `/02-skeleton/skeleton.css` на `/02-skeleton/skeleton/skeleton.css` )

2021-05-23 12:21 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton/skeleton.css
> +  height: 192px;
в данном случае пусть высота определяется внутренним содержимым блока

2021-05-23 12:21 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton/skeleton.css
> +  content: url('./../../../assets/images/ellipse.svg');
здесь всегда будет просто круг с фоном, который будет анимироваться - не стоит добавлять через иконку + через свойство content.

2021-05-23 14:44 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-23 15:00 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-23 15:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-23 15:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-23 15:04 UTC, mindk-pmishchenko commented on 04-lection2/02-skeleton/skeleton/skeleton.css
> +.skeleton {
да, наверное не за чем - это и так поддиректория 1го компонента

2021-05-23 15:09 UTC, mindk-pmishchenko commented on 04-lection2/02-skeleton/skeleton/skeleton.css
> +  content: url('./../../../assets/images/ellipse.svg');
понял, исправил

2021-05-23 15:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-23 15:10 UTC, mindk-pmishchenko commented on 04-lection2/02-skeleton/skeleton/skeleton.css
> +  height: 192px;
исправил

2021-05-23 15:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-23 15:13 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-26 10:17 UTC, GSemikozov approved these changes

2021-05-26 10:17 UTC, merged